//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car4Hire.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {

        public int cId { get; set; }


        [Required(ErrorMessage = "Please enter the your First Name")]
        [StringLength(100, MinimumLength = 1)]
        public string f_name { get; set; }

        [Required(ErrorMessage = "Please enter the your Last Name")]
        [StringLength(100, MinimumLength = 1)]
        public string l_name { get; set; }

        [Required(ErrorMessage = "Please enter the your Address")]
        [StringLength(100, MinimumLength = 1)]
        public string address { get; set; }

        [Required(ErrorMessage = "Please enter the name of your City")]
        [StringLength(100, MinimumLength = 1)]
        public string city { get; set; }

        [Required(ErrorMessage = "Please enter the your Email Address")]
        [StringLength(100, MinimumLength = 1)]
        public string email { get; set; }


        [Required(ErrorMessage = "Please enter the your Email Address")]
        [StringLength(100, MinimumLength = 1)]
        public string phone { get; set; }

        public int carId { get; set; }
    
        public virtual Car Car { get; set; }

       
    }
}
